# Generated by Django 4.1.3 on 2023-05-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0002_alter_user_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyEmail',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('verification_code', models.CharField(max_length=200)),
            ],
        ),
    ]
