# Generated by Django 4.1.3 on 2023-05-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0005_postcomment_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popularity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
