# Generated by Django 4.1.3 on 2023-05-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0006_post_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('attention_user_id', models.IntegerField()),
            ],
        ),
    ]
