# Generated by Django 4.1.3 on 2023-05-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0007_userattention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='index',
        ),
    ]
