# Generated by Django 4.2.1 on 2023-05-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0009_postlove_create_time_postsave_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postlove',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postsave',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
