# Generated by Django 4.1.3 on 2023-05-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0013_userfollow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollow',
            old_name='attention_user_id',
            new_name='follow_user_id',
        ),
    ]
