# Generated by Django 4.1.3 on 2023-05-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0014_rename_attention_user_id_userfollow_follow_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBlackList',
            new_name='UserHate',
        ),
    ]
