# Generated by Django 4.1.3 on 2023-05-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0016_rename_black_user_id_userhate_hate_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAttention',
        ),
    ]
