# Generated by Django 4.1.3 on 2023-05-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0017_delete_userattention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
    ]
