# Generated by Django 4.2.1 on 2023-05-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0018_remove_userinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('receiver_id', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
