# Generated by Django 4.1.3 on 2023-06-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0020_postvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postlove',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
