# Generated by Django 4.2.1 on 2023-06-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0021_chatmessage_isread_postcomment_isread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('channel_name', models.CharField(max_length=200)),
            ],
        ),
    ]
