# Generated by Django 4.1.3 on 2023-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0022_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
