# Generated by Django 4.1.3 on 2023-06-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchTime', '0023_alter_post_create_time_alter_postcomment_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postlove',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postsave',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
